#!/usr/bin/env bash
# Module 07: SSH — fix permissions, discover keys, generate GitHub host config

source "$(dirname "$0")/../lib/core.sh"
source "$(dirname "$0")/../lib/state.sh"

SSH_DIR="${HOME}/.ssh"
mkdir -p "$SSH_DIR"
chmod 700 "$SSH_DIR"

# Fix permissions on all private keys and collect key paths
KEY_COUNT=0
GITHUB_KEY=""
for key in "$SSH_DIR"/*; do
  [ -f "$key" ] || continue
  [[ "$key" == *.pub ]] && continue
  [[ "$(basename "$key")" == "known_hosts"* ]] && continue
  [[ "$(basename "$key")" == "authorized_keys" ]] && continue
  [[ "$(basename "$key")" == "config"* ]] && continue
  [[ "$(basename "$key")" == "environment" ]] && continue

  if ! chmod 600 "$key"; then
    mbp_log_warn "failed to set permissions on $(basename "$key")"
  fi
  KEY_COUNT=$((KEY_COUNT + 1))
  mbp_log_step "permissions 600: $(basename "$key")"

  # Pick the best key for GitHub (prefer ed25519, then rsa)
  local_name="$(basename "$key")"
  if [ -z "$GITHUB_KEY" ]; then
    GITHUB_KEY="$key"
  fi
  # Prefer developer_ed25519 (mbp convention) > id_ed25519 > any ed25519 > first key
  case "$local_name" in
    developer_ed25519) GITHUB_KEY="$key" ;;
    id_ed25519)        [[ "$(basename "$GITHUB_KEY")" != "developer_ed25519" ]] && GITHUB_KEY="$key" ;;
    *ed25519*)         [[ "$(basename "$GITHUB_KEY")" != "developer_ed25519" && "$(basename "$GITHUB_KEY")" != "id_ed25519" ]] && GITHUB_KEY="$key" ;;
  esac
done

# Warn about weak key types
if [ -n "$GITHUB_KEY" ] && [ -f "${GITHUB_KEY}.pub" ]; then
  KEY_TYPE=$(ssh-keygen -l -f "${GITHUB_KEY}.pub" 2>/dev/null | awk '{print $4}' | tr -d '()')
  KEY_BITS=$(ssh-keygen -l -f "${GITHUB_KEY}.pub" 2>/dev/null | awk '{print $1}')
  case "$KEY_TYPE" in
    DSA)
      mbp_log_warn "SSH key $(basename "$GITHUB_KEY") uses DSA which is deprecated — generate an ed25519 key"
      ;;
    RSA)
      if [ "${KEY_BITS:-0}" -lt 3072 ]; then
        mbp_log_warn "SSH key $(basename "$GITHUB_KEY") is RSA ${KEY_BITS}-bit — consider ed25519 or RSA 4096"
      fi
      ;;
  esac
fi

# Ensure config.d directory for per-client/per-project includes
mkdir -p "${SSH_DIR}/config.d"

# Generate GitHub host config from discovered keys
GITHUB_CONF="${SSH_DIR}/config.d/github.conf"
if [ -n "$GITHUB_KEY" ]; then
  cat > "$GITHUB_CONF" << EOF
# Generated by mbp — edit freely or delete to manage manually
Host github.com
    HostName github.com
    User git
    IdentityFile "${GITHUB_KEY}"
EOF
  mbp_log_ok "GitHub SSH: using $(basename "$GITHUB_KEY")"
elif [ ! -f "$GITHUB_CONF" ]; then
  mbp_log_warn "No SSH keys found — GitHub access requires a key in ~/.ssh/"
  mbp_log_warn "Generate one: ssh-keygen -t ed25519 -C \"your@email\" -f ~/.ssh/id_ed25519"
fi

# Configure 1Password SSH agent only if it's installed
OP_AGENT_SOCK="${HOME}/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
OP_CONF="${SSH_DIR}/config.d/1password.conf"
if [ -S "$OP_AGENT_SOCK" ]; then
  if [ ! -f "$OP_CONF" ]; then
    cat > "$OP_CONF" << EOF
# Generated by mbp — 1Password SSH Agent
# Remove this file if you don't use 1Password for SSH keys
Host *
    IdentityAgent "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
EOF
    mbp_log_ok "1Password SSH agent detected and configured"
  fi
elif [ -f "$OP_CONF" ]; then
  rm "$OP_CONF"
  mbp_log_step "1Password agent not found — removed stale config"
fi

mbp_log_ok "SSH: $KEY_COUNT keys secured"

state_set_module_ok "ssh"
mbp_log_ok "SSH configured"
